//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ Compatible
// This file is automatically generated by RisohEditor.
// karasunpo_res.rc

#define DLGINDEX_GETSTARTED                 0
#define DLGINDEX_LOADIMAGE                  1
#define DLGINDEX_MEASURETYPE                2
#define DLGINDEX_INPUTSTD                   3
#define DLGINDEX_STDLENGTH                  4
#define DLGINDEX_MEASURING                  5

#define IDC_PAN                             1
#define IDC_CROSS2                          2
#define IDC_LEFTRIGHT                       3
#define IDC_UPDOWN                          4
#define IDC_MOVE                            5

#define IDD_PASSWORD                        1000

#define IDM_EXIT                            1
#define IDM_ABOUT                           2
#define IDM_OPEN                            3
#define IDM_FIT_WHILE                       4
#define IDM_FIT_HORIZONTAL                  5
#define IDM_FIT_VERTICAL                    6
#define IDM_ZOOM_10PER                      7
#define IDM_ZOOM_25PER                      8
#define IDM_ZOOM_50PER                      9
#define IDM_ZOOM_75PER                      10
#define IDM_ZOOM_100PER                     11
#define IDM_ZOOM_125PER                     12
#define IDM_ZOOM_150PER                     13
#define IDM_ZOOM_200PER                     14
#define IDM_ZOOM_300PER                     15
#define IDM_ZOOM_RATE                       16
#define IDM_NEXT_PAGE                       17
#define IDM_PREV_PAGE                       18
#define IDM_GO_TO_PAGE                      19
#define IDM_PAGEDOWN                        20
#define IDM_PAGEUP                          21
#define IDM_GO_TO_HOME                      22
#define IDM_GO_TO_END                       23
#define IDM_SEG_COLOR_AUTO                  24
#define IDM_SEG_COLOR_RED                   25
#define IDM_SEG_COLOR_GREEN                 26
#define IDM_SEG_COLOR_BLUE                  27
#define IDM_RECENT_0                        28
#define IDM_RECENT_1                        29
#define IDM_RECENT_2                        30
#define IDM_RECENT_3                        31
#define IDM_RECENT_4                        32
#define IDM_RECENT_5                        33
#define IDM_RECENT_6                        34
#define IDM_RECENT_7                        35
#define IDM_ZOOM_IN                         36
#define IDM_ZOOM_OUT                        37

#define IDW_STATUS                          1
#define IDW_REALCLIENT                      2

#define ID_DEACTIVATE                       333
#define ID_ACTIVATE                         999

#define NUM_TASKS                           6

#define COMPANYNAME                         "Katayama Hirofumi MZ"
#define PROGNAME                            "karasunpo"

#ifdef APSTUDIO_INVOKED
    #ifndef APSTUDIO_READONLY_SYMBOLS
        #define _APS_NO_MFC                 1
        #define _APS_NEXT_RESOURCE_VALUE    100
        #define _APS_NEXT_COMMAND_VALUE     1000
        #define _APS_NEXT_CONTROL_VALUE     1000
        #define _APS_NEXT_SYMED_VALUE       300
    #endif
#endif
